### ISSUE TITLE
Dropcrafting doesn't function properly

### ISSUE THREAD

**Issue by Croyangi** [Cronodes/more-bosses#2]
To be fair, I have no idea how to work with item tags.
I'll just fix it later.

**Comment by CreeperMagnet** [comment]
Fix by removing drop crafting

**Comment by Jely710** [comment]
But then you wont be able to feed bruce properly :(

**Comment by Jely710** [comment]
properly*

**Comment by Croyangi** [comment]
ok jely im going to remove you

**Comment by Jely710** [comment]
darn, alright
